security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - read
        scopes:
          - "*"
      - actions:
          - create
        scopes:
          - Project
  authentication:
    providers:
      enable_native: false
      oidc:
        - slug_id: "azure"
          name: "Azure AD"
          client_id: "91818500-e2d9-49a5-8e33-f7e942992f56"
          client_secret: "XfZ8Q~hDcEr3r5bzpXQRH4-Lrjaupc3L.LFmKbZP"
          scopes:
            - "openid"
            - "profile"
            - "email"
            - "User.read"
          issuer: "https://login.microsoftonline.com/7d7761c0-8b7a-49bb-8975-a6aa1be7c38b/v2.0"
          url_params:
            domain_hint: "msp.amadeus.net"


database:
  file:
    folder: "dev/local_db"
    extension: "json"
    case_sensitive: false

provisioning:
  folders:
  - "dev/data"

schemas:
  panels_path: "schemas/panels"
  queries_path: "schemas/queries"
  datasources_path: "schemas/datasources"
  variables_path: "schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "perses"
    dashboard: "Demo"
  - project: "testing"
    dashboard: "DuplicatePanels"
  - project: "Unknown"
    dashboard: "Dashboard"

information: |-
  # Hello World
  ## File Database setup
